
package com.masnegocio.mcdonalds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "McDonalds", targetNamespace = "http://www.masnegocio.com/McDonalds/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface McDonalds {


    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerarFactura", action = "http://www.masnegocio.com/McDonalds/GenerarFactura")
    @WebResult(name = "respuesta", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
    public String generarFactura(
        @WebParam(name = "cadenajson", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
        String parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaFactura", action = "http://www.masnegocio.com/McDonalds/ConsultaFactura")
    @WebResult(name = "respuesta", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
    public String consultaFactura(
        @WebParam(name = "consulta", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
        String parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaFactura", action = "http://www.masnegocio.com/McDonalds/EnviaFactura")
    @WebResult(name = "respuestaemail", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
    public String enviaFactura(
        @WebParam(name = "enviaemail", targetNamespace = "http://www.masnegocio.com/McDonalds/", partName = "parameter")
        String parameter);

}
